<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { api } from '../services/api'
import KpiCard from '../components/KpiCard.vue'
import Panel from '../components/Panel.vue'
import { timeAgo, severityClass } from '../utils/format'

const data = ref(null)
let timer = null

async function load() {
  try { data.value = await api.overview() } catch (e) { /* keep last */ }
}
onMounted(() => { load(); timer = setInterval(load, 5000) })
onUnmounted(() => clearInterval(timer))

const baseBar = (categories, color) => ({
  chart: { type: 'bar', height: 240, toolbar: { show: false }, fontFamily: 'inherit' },
  plotOptions: { bar: { borderRadius: 4, columnWidth: '55%' } },
  dataLabels: { enabled: false },
  colors: [color],
  grid: { borderColor: '#eef2f7' },
  xaxis: { categories, labels: { rotate: -45, style: { fontSize: '10px' } } }
})
const baseLine = (categories, color) => ({
  chart: { type: 'area', height: 240, toolbar: { show: false }, fontFamily: 'inherit' },
  stroke: { curve: 'smooth', width: 2 },
  fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.4, opacityTo: 0.05 } },
  dataLabels: { enabled: false },
  colors: [color],
  grid: { borderColor: '#eef2f7' },
  xaxis: { categories, labels: { rotate: -45, style: { fontSize: '10px' } } }
})

const msgChart = computed(() => ({
  options: baseBar((data.value?.messagesPerMinute ?? []).map(p => p.label), '#2563eb'),
  series: [{ name: 'Messages', data: (data.value?.messagesPerMinute ?? []).map(p => p.value) }]
}))
const alertChart = computed(() => ({
  options: baseBar((data.value?.alertsPerHour ?? []).map(p => p.label), '#dc2626'),
  series: [{ name: 'Alerts', data: (data.value?.alertsPerHour ?? []).map(p => p.value) }]
}))
const hrChart = computed(() => ({
  options: baseLine((data.value?.heartRateTrend ?? []).map(p => p.label), '#0ea5e9'),
  series: [{ name: 'Avg HR', data: (data.value?.heartRateTrend ?? []).map(p => p.value) }]
}))
const tempChart = computed(() => ({
  options: baseLine((data.value?.temperatureTrend ?? []).map(p => p.label), '#0d9488'),
  series: [{ name: 'Avg Temp', data: (data.value?.temperatureTrend ?? []).map(p => p.value) }]
}))
</script>

<template>
  <div v-if="data" class="grid" style="gap:18px;">
    <div class="grid kpis">
      <KpiCard label="Total Patients" :value="data.totalPatients" icon="👥" tone="blue" meta="Registered in roster" />
      <KpiCard label="Active Patients" :value="data.activePatients" icon="💓" tone="green" meta="Reporting in last 2 min" />
      <KpiCard label="Critical Alerts" :value="data.criticalAlerts" icon="🚨" tone="red" meta="Critical severity" />
      <KpiCard label="Avg Heart Rate" :value="data.averageHeartRate + ' bpm'" icon="❤" tone="sky" meta="Across active patients" />
      <KpiCard label="Avg Temperature" :value="data.averageTemperature + '°C'" icon="🌡" tone="teal" meta="Across active patients" />
      <KpiCard label="Avg SpO₂" :value="data.averageSpo2 + '%'" icon="🫁" tone="blue" meta="Across active patients" />
    </div>

    <div class="grid cols-2">
      <Panel title="Messages Processed / Minute" hint="pipeline throughput">
        <apexchart type="bar" height="240" :options="msgChart.options" :series="msgChart.series" />
      </Panel>
      <Panel title="Alerts / Hour" hint="generated by rules">
        <apexchart type="bar" height="240" :options="alertChart.options" :series="alertChart.series" />
      </Panel>
      <Panel title="Average Heart Rate Trend">
        <apexchart type="area" height="240" :options="hrChart.options" :series="hrChart.series" />
      </Panel>
      <Panel title="Average Temperature Trend">
        <apexchart type="area" height="240" :options="tempChart.options" :series="tempChart.series" />
      </Panel>
    </div>

    <div class="grid cols-2">
      <Panel title="Latest Sensor Readings">
        <div v-if="!data.recentReadings.length" class="empty">No readings yet…</div>
        <table v-else>
          <thead><tr><th>Patient</th><th>Room</th><th>Reading</th><th>When</th></tr></thead>
          <tbody>
            <tr v-for="(e, i) in data.recentReadings" :key="i">
              <td>{{ e.patientId }}</td>
              <td class="mono">{{ e.roomNumber }}</td>
              <td class="muted">{{ e.text }}</td>
              <td class="muted">{{ timeAgo(e.timestamp) }}</td>
            </tr>
          </tbody>
        </table>
      </Panel>
      <Panel title="Latest Alerts">
        <div v-if="!data.recentAlerts.length" class="empty">No alerts yet…</div>
        <table v-else>
          <thead><tr><th>Patient</th><th>Severity</th><th>Message</th><th>When</th></tr></thead>
          <tbody>
            <tr v-for="(e, i) in data.recentAlerts" :key="i">
              <td>{{ e.patientId }}</td>
              <td><span class="badge" :class="severityClass(e.severity)">{{ e.severity }}</span></td>
              <td class="muted">{{ e.text }}</td>
              <td class="muted">{{ timeAgo(e.timestamp) }}</td>
            </tr>
          </tbody>
        </table>
      </Panel>
    </div>
  </div>
  <div v-else class="empty">Loading overview…</div>
</template>
