<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useRealtime } from './stores/realtime'

const rt = useRealtime()
const route = useRoute()
const menuOpen = ref(false)

const nav = [
  { to: '/', icon: '📊', label: 'Overview' },
  { to: '/live', icon: '💓', label: 'Live Monitoring' },
  { to: '/patients', icon: '🧑‍⚕️', label: 'Patient Details' },
  { to: '/alerts', icon: '🚨', label: 'Alert Center' },
  { to: '/analytics', icon: '📈', label: 'Analytics' },
  { to: '/ai', icon: '🤖', label: 'AI Predictions' },
  { to: '/system', icon: '🩺', label: 'System Health' }
]

const title = computed(() => route.meta.title ?? 'Dashboard')
const subtitle = computed(() => ({
  'Overview': 'Real-time situational awareness across all monitored patients',
  'Live Monitoring': 'Streaming vitals with automatic status classification',
  'Patient Details': 'Per-patient vitals, statistics and AI risk assessment',
  'Alert Center': 'Clinical alerts generated by the processing layer',
  'Analytics': 'Windowed aggregations and risk leaderboards',
  'AI Predictions': 'Heart-attack risk prediction (ML.NET)',
  'System Health': 'Pipeline throughput and performance metrics'
}[title.value] ?? ''))

const connLabel = computed(() => ({ live: 'Live', connecting: 'Connecting…', down: 'Reconnecting…' }[rt.status]))

onMounted(() => rt.init())
</script>

<template>
  <div class="shell">
    <div v-if="menuOpen" class="scrim" @click="menuOpen = false"></div>
    <aside class="sidebar" :class="{ open: menuOpen }">
      <div class="brand">
        <div class="logo">❤</div>
        <div>
          <h1>Smart Health</h1>
          <small>IoT Monitoring · Vue</small>
        </div>
      </div>
      <RouterLink v-for="n in nav" :key="n.to" :to="n.to" class="nav-link" @click="menuOpen = false">
        <span class="ic">{{ n.icon }}</span>{{ n.label }}
      </RouterLink>
      <div class="sidebar-foot">
        Sensor → Kafka → Spark → Cassandra → API → Dashboard<br />
        Self-contained demo · auto-generating data
      </div>
    </aside>

    <div class="main">
      <header class="topbar">
        <div style="display:flex;align-items:center;gap:14px;">
          <button class="menu-btn" @click="menuOpen = !menuOpen">☰</button>
          <div>
            <h2>{{ title }}</h2>
            <div class="sub">{{ subtitle }}</div>
          </div>
        </div>
        <div class="conn">
          <span class="dot" :class="{ live: rt.status === 'live', down: rt.status === 'down' }"></span>
          {{ connLabel }}
        </div>
      </header>
      <main class="content">
        <RouterView v-slot="{ Component }">
          <component :is="Component" />
        </RouterView>
      </main>
    </div>
  </div>
</template>
